### ISSUE TITLE
Add dark mode 🌓

### ISSUE THREAD

**Issue by nurcinozer** [nurcinozer/gist-blog#5]
📋 Request Details

Add dark mode and light mode to the website. It will be great if we can add a toggle button on the top right corner of the website. For details, you can check [this](https://javascript.plainenglish.io/how-to-create-light-and-dark-mode-toggle-in-next-js-with-tailwind-61e67518fd2d) out.

**Comment by Siddhanthota** [comment]
Can you assign this to me? I would love to work on this.
